"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
"""


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        # create dict that holds letters in s
        s_chars = {}

        for char in s:
            if s_chars.get(char) is None:
                s_chars[char] = 0
            s_chars[char] += 1

        for char in t:
            if s_chars.get(char) is None or s_chars.get(char) == 0:
                return char
            s_chars[char] -= 1
